module.exports = {
  CHANGE_MODE: 'CHANGE_MODE',
  CACHE_LIVE_LIST: 'CACHE_LIVE_LIST',
  CHANGE_GAME_SELECT_INDEX: 'CHANGE_GAME_SELECT_INDEX',
  CHANGE_LIVE_SELECT_INDEX: 'CHANGE_LIVE_SELECT_INDEX',
  CHANGE_CURRENT_PAGE_INDEX: 'CHANGE_CURRENT_PAGE_INDEX'
};
